### ISSUE TITLE
why can't I use this?

### ISSUE THREAD

**Issue by rebotak** [soraino/v-autosuggest#1]
@soraino, I'm pretty sure already installed the package thru

 `npm install --save v-autosuggest` 

and import on my `main.js` 

```
import VAutosuggest from 'v-autosuggest'
Vue.component('v-autosuggest', VAutosuggest )
```

but this error keep showing up and telling me the dependency not found whenever I run my project.

![image](https://user-images.githubusercontent.com/804078/36636909-64c60344-1a02-11e8-8e07-b13b17d1c680.png)

**Comment by soraino** [comment]
Maybe you should check your package.json file and see if the package has been added into the `dependencies` section.

**Comment by rebotak** [comment]
it's there in my package.json. and I'm already tried to delete `node_modules` folder and re-run the npm install and result's still same. 

![image](https://user-images.githubusercontent.com/804078/36638446-da39f520-1a27-11e8-91d9-60e8e50bce1f.png)

**Comment by rebotak** [comment]
also `v-autosuggest` is already inside my `node_modules` folder... 😶

![image](https://user-images.githubusercontent.com/804078/36638456-559b77fc-1a28-11e8-8be7-e80a2c60da2f.png)

**Comment by soraino** [comment]
erm... this is weird, try reinstall all the node module.
Deleted the `node_modules` folder and then `npm install`

**Comment by rebotak** [comment]
tried it, but still same. have you tried to remove yours and reinstall?

**Comment by soraino** [comment]
Yeah, I've even tried deleted the whole project and creating it but i still cannot produce your error.
I don't think it is a NPM error and i don't really know what is happening.
Not sure how deep you're already into this project, you can try deleting the project and starting over again and see if it works?

**Comment by rebotak** [comment]
okaay, will try to init new project and add this. and see how it's going. thanks for your advice
