### ISSUE TITLE
Issue for linux users

### ISSUE THREAD

**Issue by StanislavNaumov** [soraino/v-autosuggest#3]
There is an issue for linux users.
Linux user will have to rename 'AutoSuggest.vue' to 'Autosuggest.vue' because when you will try to import this module it won't be able to find an 'Autosuggest.vue'

**Comment by soraino** [comment]
Oh really, is it an FS problem because I've never heard of a naming issue before?

**Comment by StanislavNaumov** [comment]
Yes, it is. For linux file system 'AutoSuggest.vue' and 'Autosuggest.vue' are different file names and files.

**Comment by MaFx** [comment]
https://github.com/soraino/v-autosuggest/pull/4 opened to fix this issue.
