### ISSUE TITLE
Can't use bootstrap classes

### ISSUE THREAD

**Issue by Jalibk001** [soraino/v-autosuggest#7]
Hi there,
Kindly add a prop where we can add bootstrap classes like "form-control", currently I tried overriding the already created css, but it still doesn't give required results. Please look into this.
Thanks

**Comment by soraino** [comment]
This is a problem with the input box right? Not the suggestion box, since you can substitute it with your custom components it.

**Comment by Jalibk001** [comment]
Yes this is a problem with the input box, but I think it should have an option for accepting classes in the form of props. Kindly elaborate how I can substitute it with my custom components.

**Comment by soraino** [comment]
Do look at the advance usage section, I provided some examples of using custom-built components on how you want to display your suggested item. There's an optional prop declaration called suggItemComp which you can put in.

**Comment by soraino** [comment]
you can now add your custom class by passing the class string into `inputClass ` prop like this:
`<VAutoSuggest
      v-model="searchData"
      :suggValue="'name'"
      :inputClass="'form-control'"
      :items="staticSuggArray"
    />`

**Comment by Jalibk001** [comment]
Thanks
Kindly add this to the documentation as well
